require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-graphql
  - rubocop-minitest
  - rubocop-ordered_methods
  - rubocop-rails

AllCops:
  NewCops: enable

GraphQL/ArgumentDescription:
  Enabled: false

GraphQL/ExtractInputType:
  Enabled: false

GraphQL/ExtractType:
  Enabled: false

GraphQL/FieldDescription:
  Enabled: false

GraphQL/MaxComplexitySchema:
  Enabled: false

GraphQL/MaxDepthSchema:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
