export const UOM: { [key: string]: string } = {
  tonne: "Tonne",
  kilograms: "Kilograms",
  grams: "Grams",
  decagram: "Decagram",
  decigram: "Decigram",
  centigram: "Centigram",
  milligram: "Milligram",
  kilolitre: "Kilolitre",
  hectolitre: "Hectolitre",
  decalitre: "Decalitre",
  litre: "Litre",
  decilitre: "Decilitre",
  centilitre: "Centilitre",
  millilitre: "Millilitre",
  pound: "Pound",
  ounce: "Ounce",
  grain: "Grain",
  item: "Item",
};
